# Generated by Django 3.2.4 on 2021-06-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('reminder', models.BooleanField()),
            ],
        ),
    ]
