# Generated by Django 3.2.4 on 2021-06-26 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='reminder',
            new_name='completed',
        ),
    ]
